# Generated by Django 2.1.5 on 2019-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('short_url', models.TextField(unique=True)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
